---

- name: Create MapR Group
  become: true 
  group:
    name: "{{ mapr_group }}"
    gid: "{{ mapr_group_gid }}"
    state: present
- name: Create MapR User
  become: true 
  user:
    name: "{{ mapr_user }}"
    comment: "MapR default user"
    uid: "{{ mapr_user_uid }}"
    group: "{{mapr_group}}"
    groups: "{{ mapr_group }}"
    password: "{{ mapr_passwd }}"
    createhome: true
    update_password: on_create
    state: present
    append: true
#   groups={{ mapr_group }},root,wheel
