---
- name: Install required Ansible package to handle SElinux
  become: true 
  package: name=libselinux-python state=present
  when: ansible_os_family != 'Suse'
- name: Disable SElinux
  selinux: state=disabled
  when: ansible_os_family != 'Suse'
