---
# Oracle JDK playbook
- name: Downloading Java JDK
  become: true  
  get_url:
    url: "{{oracle_jdk_url}}"
    force: true
    mode: 0440
    headers: "Cookie:oraclelicense=accept-securebackup-cookie"
    dest: /tmp/oracle-jdk.tar.gz
    timeout: 120

- name: Create /opt/java
  become: true  
  file:
    path: /opt/java
    mode: 0755
    state: directory
- name: Install Java JDK
  become: true  
  unarchive:
    src: /tmp/oracle-jdk.tar.gz
    dest: /opt/java
    copy: false
- name: Create link /usr/bin/java
  become: true  
  file:
    src: "{{jdk_folder}}/bin/java"
    dest: /usr/bin/java
    state: link
# Other actions
- name: Copy Local Policy
  become: true  
  copy:
    src: "../files/UnlimitedJCEPolicyJDK8/local_policy.jar"
    dest: "{{jdk_folder}}/jre/lib/security/"
    mode: 0644
# - name: Copy US Export Policy
#  copy:
#    src: "../files/UnlimitedJCEPolicyJDK8/US_export_policy.jar"
#    dest: "{{jdk_folder}}/jre/lib/security/"
#    mode: 0644
- name: Add JAVA_HOME to /etc/profile
  become: true  
  lineinfile:
    dest: /etc/profile
    state: present
    line: "export JAVA_HOME={{jdk_folder}}"


#  - name: Copy /etc/environment with java and path settings
#    copy:
#      src: "../files/environment"
#      dest: "/etc/environment"
