---
# Uninstall MAST Gateway
- name: Check for mapr-clusters.conf
  stat: path=/opt/mapr/conf/mapr-clusters.conf
  register: clusters_conf
  become: true
- name: Stop MAST Gateway
  shell: "maprcli node services -name mastgateway -action stop -nodes {{ ansible_fqdn }}"
  register: maprcli_result
  failed_when: maprcli_result.rc > 1
  changed_when: maprcli_result.rc == 0
  environment:
    MAPR_TICKETFILE_LOCATION: /opt/mapr/conf/mapruserticket
  when: clusters_conf.stat.exists
  become: true
- name: Uninstall mapr-mastgateway
  package: name=mapr-mastgateway state=absent
  become: true
  
