---
- name: Find Hadoop YARN server JARs
  become: true 
  find: paths="/opt/mapr/hadoop/hadoop-{{ hadoop_version }}/share/hadoop/yarn/" patterns="hadoop-yarn-server-*" file_type=file
  register: yarnserver_jar_path_result
  failed_when: yarnserver_jar_path_result.matched == 0
- name: Transform to Hadoop YARN server JARs list
  become: true 
  set_fact: yarnserver_jars_list={{ yarnserver_jar_path_result.files | map(attribute='path') | list }}
- debug: msg="Find Hadoop YARN server JARs {{ item | basename }}"
  with_items: "{{ yarnserver_jars_list }}"
- name: Copy Jars to local, required for Hive Server and Spark
  become: true 
  fetch: src="{{ item }}" dest="{{ local_tmp_path }}/{{ item | basename }}" flat=yes
  with_items: "{{ yarnserver_jars_list }}"
  when: inventory_hostname == groups["mapr-cldb"][0]
