- name: Remove existing GPG key file if it exists
  become: true
  ansible.builtin.file:
    path: "/tmp/maprgpg.key"
    state: absent
  when: ansible_os_family in ['RedHat', 'Debian']

- name: Download the MapR GPG Key for RedHat
  become: true
  ansible.builtin.get_url:
    url: "{{ mapr_gpg_key_url }}"
    dest: "/tmp/maprgpg.key"
    headers:
      Authorization: "Basic {{ (mapr_email + ':' + mapr_token) | b64encode }}"
  when: ansible_os_family == 'RedHat'
- name: Remove broken repository from sources.list
  become: true
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list
    regexp: 'deb https://package.ezmeral.hpe.com/releases/'
    state: absent
  when: ansible_distribution == "Ubuntu"

- name: Remove broken MEP repository from sources.list
  become: true
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list
    regexp: 'deb https://package.ezmeral.hpe.com/releases/MEP'
    state: absent
  when: ansible_distribution == "Ubuntu"


- name: Update package cache
  become: true
  apt:
    update_cache: yes
  when: ansible_os_family == 'Debian' 

- name: Import RPM key for RedHat
  become: true
  ansible.builtin.rpm_key:
    state: present
    key: "/tmp/maprgpg.key"
  when: ansible_os_family == 'RedHat'

- name: Download the MapR GPG Key for Ubuntu
  become: true
  ansible.builtin.get_url:
    url: "{{ mapr_gpg_key_url }}"
    dest: "/tmp/maprgpg.key"
    headers:
      Authorization: "Basic {{ (mapr_email + ':' + mapr_token) | b64encode }}"
  when: ansible_os_family == 'Debian'

- name: Add the MapR GPG Key for Ubuntu
  become: true
  ansible.builtin.command:
    cmd: apt-key add /tmp/maprgpg.key
  become: true
  when: ansible_os_family == 'Debian'
- name: Create apt auth.conf for Data Fabric Repository
  become: true
  ansible.builtin.copy:
    dest: /etc/apt/auth.conf.d/package.ezmeral.hpe.com.conf
    content: |
      machine package.ezmeral.hpe.com
      login {{ mapr_email }}
      password {{ mapr_token }}
  become: true
  when: ansible_os_family == 'Debian'
- name: Add Data Fabric Release Repository to sources.list
  become: true
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list
    line: "deb {{ mapr_release_url }}/ubuntu/ binary bionic"
    create: yes
  become: true
  when: ansible_os_family == 'Debian'

- name: Add Data Fabric Ecosystem Repository to sources.list
  become: true
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list
    line: "deb {{ mapr_ecosystem_url }}/ubuntu/ binary bionic"
    create: yes
  become: true
  when: ansible_os_family == 'Debian'
- name: Update apt package indexes
  become: true
  ansible.builtin.apt:
    update_cache: yes
  become: true
  when: ansible_os_family == 'Debian'



- name: Add Data Fabric repository to sources.list
  become: true
  ansible.builtin.blockinfile:
    path: /etc/apt/sources.list
    block: |
      deb https://package.ezmeral.hpe.com/releases/v{{ data_fabric_version }}/ubuntu/ binary  bionic
      deb https://package.ezmeral.hpe.com/releases/MEP/MEP-{{ mep_version }}/ubuntu/ binary bionic
    marker: "# {mark} ANSIBLE MANAGED BLOCK - HPE Data Fabric"
  when: ansible_distribution == "Ubuntu"

- name: Update apt package index
  become: true
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
  
- name: Ensure syslinux is installed
  become: true
  ansible.builtin.package:
    name: syslinux
    state: present