---
- name: Install RPC bind
  become: true 
  package: name=rpcbind state=present

# Other actions
- name: Start the RPC bind service
  become: true 
  service: name=rpcbind state=started enabled=yes
