- name: Install OpenJDK 11
  become: yes  # This will elevate the privilege to root for the task
  vars:
    packages_RedHat: ['java-11-openjdk', 'java-11-openjdk-devel', 'java-11-openjdk-headless']
    packages_Debian: ['openjdk-11-jdk'] # OpenJDK 11 for Debian/Ubuntu
    packages_Suse: ['java-11-openjdk', 'java-11-openjdk-devel']
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ vars['packages_' + ansible_os_family] }}"
- name: Set JAVA_HOME environment variable
  become: yes
  lineinfile:
    path: /etc/environment
    line: 'JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"'
    state: present
