- name: Install MySQL
  become: true
  hosts: ext-mysql
  roles:
    - ../roles/ext-mysql-install
- name: Uninstall MySQL
  hosts: all:!ext-mysql
  roles:
    - ../roles/ext-mysql-uninstall
  become: true